resolver: lts-18.8
packages:
  - .
  - example-project
nix:
  packages:
    - zlib.dev
    - zlib.out
# Work around https://github.com/commercialhaskell/stack/issues/5290
save-hackage-creds: false
extra-deps:
  - github: brendanhay/amazonka
    commit: 098795f847df7239af64535c6b2b233f3fbd699c
    subdirs:
      - lib/amazonka
      - lib/amazonka-core
      - lib/services/amazonka-sts # amazonka library depends on this
      - lib/services/amazonka-kinesis
      - lib/services/amazonka-s3
